name: Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.parallel=false
      KEY1: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    steps:
      - name: List files
        run: echo $GITHUB_WORKSPACE

      - name: Make key file
        run: echo $KEYSTORE_BASE64 | base64 -d > a.key

      - name: List working-directory
        run: ls -la
        
      - name: Assign values
        env:
          MYMSG: "Simple message\n"
        run: 
          echo $KEY
          echo $MYMSG
          echo "Last line"

      - name: Check result
        if: ${{ env.KEY1 == '' }}
        run: echo "Empty key!"
