name: Test
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.parallel=false

    steps:

      - name: Test
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo "$KEYSTORE_BASE64" | base64 -d > /dev/null
